Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/11/2023
Var
contador, resto:inteiro


Inicio


contador <- 100

repita
      resto <- contador % 2
      se ( resto = 0 ) entao
      escreval ( contador )
      fimse
      contador <- contador + 2
      ate ( contador > 200 )



Fimalgoritmo