Algoritmo "questao2"
//2) Desenvolver um programa que exiba os números em ordem decrescente de 100 até 1
Var
// Seção de Declarações das variáveis
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Exibindo os números de 1 até 100")
contador <- 100

enquanto ( contador = 1)faca
         escreval( contador )
         contador <- contador - 1

fimenquanto

Fimalgoritmo