Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/10/2023
Var
acrecimo, valor: real


Inicio
escreval("Informe o valor da conta: ")
leia(valor)

acrecimo <- valor + valor * 0.10

escreva("O valor com acréscimo do garçom é: ", acrecimo)


Fimalgoritmo